# Previewをみたい場合はSHIPT + ALT + Pを実行してください。
openapi: 3.0.3
info:
  title: AI Lab ALL APIs
  description: |-
    参考のリンク:
      - [swagger editorのリンク version:3.03](https://editor.swagger.io/)
  version: 1.0.0
tags:
  - name: user
    description: Every thing about users
paths:
  /user:
    post:
      tags:
        - user
      summary: Get a list of users
      responses:
        '200':
          description: A list of usersX
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: Update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
    delete:
      tags:
        - user
      summary: Delete user
      description: ログインしているユーザによって実行される
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: 山田太郎
        email:
          type: string
          example: yamada@email.com
        password:
          type: string
          example: '1243'
